# @package _global_
config:
  METERS:
    accuracy_list:
      num_list: 1
      topk: [1, 5]
  MODEL:
    EVAL_FEATURES: ["res5"]
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNETS:
          # RegNetY 400Mflops
          BN:
            EPSILON: 1.0e-5
            MOMENTUM: 0.1
            NUM_SAMPLES_PRECISE: 1024
            USE_PRECISE_STATS: false
          MEM:
            RELU_INPLACE: true
          MODEL:
            TYPE: "uninet"
            NUM_CLASSES: 1000
          UNINET:
            ACT_FUN: "relu"
            ANYNET_NEW_HPS: []
            B31_RELU_A: true
            B31_RELU_B: true
            B3N_1X1: true
            B3N_N: 1
            BLOCK_TYPE: "res_cut_gw"
            BOT_MULS: [1.0, 1.0, 1.0, 1.0]
            BW_DIV8: false
            BW_WRT_OW: true
            DEPTHS: [2, 4, 9, 7]
            DWISE_3X3: false
            GROUP_WS: [32, 32, 32, 32]
            HARD_SWISH_CAP: true
            HARD_SWISH_DIVIDE: true
            HARD_SWISH_SHIFT: true
            LIN_PROJ: false
            NUM_GS: []
            REGNET_DM: 1.0
            REGNET_NEW_HPS: []
            REGNET_WM: 1.0
            RELU_3X3: true
            SE_ENABLED: true
            SE_POSITION: 2
            SE_RATIO: 0.25
            STEM_TYPE: "simple_stem_in"
            STEM_W: 32
            STRIDES: [2, 2, 2, 2]
            TRANS_TYPE: "bottleneck_transform"
            WIDTHS: [32, 64, 128, 288]
            WS_QUANTIZATION: 8
      LINEAR_FEAT_POOL_OPS: [
          ["AdaptiveAvgPool2d", [[6, 5]]],
      ]
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 288, "dims": [8640, 1000]}],
      ]
