# @package _global_
config:
  DATA:
    TRAIN:
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: RandomCrop
          size: 227
        - name: RandomHorizontalFlip
        - name: ImgPil2LabTensor
    TEST:
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 227
        - name: ImgPil2LabTensor
  MODEL:
    INPUT_TYPE: lab
    TRUNK:
      NAME: alexnet_colorization
      LINEAR_FEAT_POOL_OPS: [
          ["AvgPool2d", [[19, 19], 4, 0]],
          ["AvgPool2d", [[12, 12], 3, 0]],
          ["AvgPool2d", [[9, 9], 1, 0]],
          ["AvgPool2d", [[9, 9], 1, 0]],
          ["AvgPool2d", [[8, 8], 1, 0]],
      ]
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 96, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 8142]}],
        ["eval_mlp", {"in_channels": 384, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 384, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 8142]}],
      ]
  OPTIMIZER:
    nesterov: True
    regularize_bn: False
    regularize_bias: False
