# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNETS:
          # RegNetY 256 GFlops
          # "input_pythcls_config": "/mnt/vol/gfsai-bistro2-east/ai-group/bistro/gpu/kosaraju/nms2/sweeps/dds_w0/train_cfgs/imagenet/8gpu/RegNet-Y-E100-FB256-V04-LP0-SW0-SE1-BS128/1.0_1.0_1.0_1.0_3_7_16_1_640_848_848_848_640_1696_2544_5088.yaml"
          BN:
            EPSILON: 1.0e-5
            MOMENTUM: 0.1
            NUM_SAMPLES_PRECISE: 1024
            USE_PRECISE_STATS: false
          MEM:
            RELU_INPLACE: true
          MODEL:
            TYPE: "uninet"
            NUM_CLASSES: 1000
          UNINET:
            ACT_FUN: "relu"
            ANYNET_NEW_HPS: []
            B31_RELU_A: true
            B31_RELU_B: true
            B3N_1X1: true
            B3N_N: 1
            BLOCK_TYPE: "res_cut_gw"
            BOT_MULS: [1.0, 1.0, 1.0, 1.0]
            BW_DIV8: false
            BW_WRT_OW: true
            DEPTHS: [3, 7, 16, 1]
            DWISE_3X3: false
            GROUP_WS: [640, 848, 848, 848]
            HARD_SWISH_CAP: true
            HARD_SWISH_DIVIDE: true
            HARD_SWISH_SHIFT: true
            LIN_PROJ: false
            NUM_GS: []
            REGNET_DM: 1.0
            REGNET_NEW_HPS: []
            REGNET_WM: 1.0
            RELU_3X3: true
            SE_ENABLED: true
            SE_POSITION: 2
            SE_RATIO: 0.25
            STEM_TYPE: "simple_stem_in"
            STEM_W: 32
            STRIDES: [2, 2, 2, 2]
            TRANS_TYPE: "bottleneck_transform"
            WIDTHS: [640, 1696, 2544, 5088]
            WS_QUANTIZATION: 8
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [5088, 5088], "use_relu": True}],
        ["mlp", {"dims": [5088, 128], "use_relu": False}],
      ]
