 # @package _global_
 config:
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 101
          ######## resnext101-32x4d #######
          # GROUPS: 32
          # WIDTH_PER_GROUP: 4
          ######## resnext101-32x8d #######
          # GROUPS: 32
          # WIDTH_PER_GROUP: 8
          ######## resnext101-32x16d #######
          # GROUPS: 32
          # WIDTH_PER_GROUP: 16
      LINEAR_FEAT_POOL_OPS: [
          ["AvgPool2d", [[10, 10], 10, 4]],
          ["AvgPool2d", [[16, 16], 8, 0]],
          ["AvgPool2d", [[13, 13], 5, 0]],
          ["AvgPool2d", [[8, 8], 3, 0]],
          ["AvgPool2d", [[6, 6], 1, 0]],
      ]
    HEAD:
      PARAMS: [["mlp", {"dims": [2048, 20]}]]
