# @package _global_
config:
  MODEL:
    HEAD:
      PARAMS: [
      ["vision_transformer_head", {"in_plane": 1024, "hidden_dim": 4096,
                                   "num_classes": 1000}],
      ]