# @package _global_
config:
  DATA:
    TRAIN:
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: RandomCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: ImgPil2LabTensor
    TEST:
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ImgPil2LabTensor
  MODEL:
    INPUT_TYPE: lab
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
          LAYER4_STRIDE: 1
      LINEAR_FEAT_POOL_OPS: [
          ["AvgPool2d", [[10, 10], 10, 4]],
          ["AvgPool2d", [[16, 16], 8, 0]],
          ["AvgPool2d", [[13, 13], 5, 0]],
          ["AvgPool2d", [[8, 8], 3, 0]],
          ["AvgPool2d", [[12, 12], 2, 0]],
      ]
    HEAD:
      PARAMS: [["mlp", {"dims": [2048, 4]}]]
