 # @package _global_
 config:
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
          WIDTH_MULTIPLIER: 3
      LINEAR_FEAT_POOL_OPS: [
          ########## res50-w3 #############
          ["AdaptiveAvgPool2d", [7]],
          ["AdaptiveAvgPool2d", [[4, 3]]],
          ["AdaptiveAvgPool2d", [[3, 2]]],
          ["AdaptiveAvgPool2d", [[3, 1]]],
          ["AdaptiveAvgPool2d", [[2, 1]]],
      ]
    HEAD:
      PARAMS: [["mlp", {"dims": [6144, 20]}]]
