# @package _global_
config:
  MODEL:
    HEAD:
      PARAMS: [
      ["mlp", {"dims": [768, 3072], "use_relu": True, "use_bn": True, "use_bias": False}],
      ["mlp", {"dims": [3072, 1000]}],
      ]