# @package _global_
config:
  DATA:
    TRAIN:
      BATCHSIZE_PER_REPLICA: 64
  OPTIMIZER:
    param_schedulers:
      lr:
        base_value: 28.8
        name: composite
        schedulers:
          - name: linear
            start_value: 0.6
            end_value: 28.8
          - name: cosine
            start_value: 28.8
            end_value: 0.0000
        update_interval: step
  DISTRIBUTED:
    NUM_NODES: 48
    NUM_PROC_PER_NODE: 8
