# @package _global_
config:
  TENSORBOARD_SETUP:
    USE_TENSORBOARD: True
    EXPERIMENT_LOG_DIR: "/checkpoint/ito/vision_transformer/8gpu_test"
    LOG_ACTIVATIONS: False
    FLUSH_EVERY_N_MIN: 20
  CHECKPOINT:
    DIR: "/checkpoint/ito/vision_transformer/8gpu_test"
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 1
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TRAIN:
      DATA_SOURCES: [disk_folder]
      #      DATA_PATHS: ["<path to train folder>"]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 16
      TRANSFORMS:
        - name: RandomResizedCrop
          size: 224
        #        - name: RandomHorizontalFlip
        #        - name: ColorJitter
        #          brightness: 0.4
        #          contrast: 0.4
        #          saturation: 0.4
        #          hue: 0.4
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    TEST:
      DATA_SOURCES: [disk_folder]
      #      DATA_PATHS: ["<path to test folder>"]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 16
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  MODEL:
    TRUNK:
      NAME: vision_transformer
      TRUNK_PARAMS:
        VISION_TRANSFORMERS:
          NUM_LAYERS: 12
          NUM_HEADS: 12
          HIDDEN_DIM: 768
          MLP_DIM: 3072
          DROPOUT_RATE: 0.1
          ATTENTION_DROPOUT_RATE: 0
          CLASSIFIER: token
    HEAD:
      PARAMS: [
      ["vision_transformer_head", {"in_plane": 768, "hidden_dim": 3072,
                                   "num_classes": 1000}],
      ]
  LOSS:
    name: cross_entropy_multiple_output_single_target
    cross_entropy_multiple_output_single_target:
      ignore_index: -1
  OPTIMIZER:
    name: adamw
    weight_decay: 0.3
    #    momentum: 0.9
    num_epochs: 300
    #    nesterov: True
    #    regularize_bn: False
    #    regularize_bias: True
    param_schedulers:
      lr:
        #        auto_lr_scaling: # learning rate is automatically scaled based on batch size
        #          auto_scale: true
        #          base_value: 0.1
        #          base_lr_batch_size: 256 # learning rate of 0.1 is used for batch size of 256
        name: composite
        schedulers:
          - name: linear
            start_value: 0.00001
            end_value: 0.003
          - name: linear
            start_value: 0.003
            end_value: 0.000001
        interval_scaling: [rescaled, fixed]
        update_interval: step
        lengths: [0.1, 0.9]                 # 100ep, 10% of training is used for warmup.
  GRAD_CLIP:
    USE_GRAD_CLIP: True
  METERS:
    accuracy_list_meter:
      num_meters: 1
      topk_values: [1, 5]
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 8 # 1 GPU
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  VERBOSE: True
  LOG_FREQUENCY: 100
  TEST_ONLY: False
  TEST_EVERY_NUM_EPOCH: 1
  TEST_MODEL: True
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: fork
