# @package _global_
config:
  VERBOSE: True
  LOG_FREQUENCY: 10
  TEST_ONLY: False
  TEST_MODEL: False
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  MONITOR_PERF_STATS: True
  ROLLING_BTIME_FREQ: 313
  PERF_STAT_FREQUENCY: 10
  #  TEST_EVERY_NUM_EPOCH: 1
  #  TEST_MODEL: True
  TENSORBOARD_SETUP:
    USE_TENSORBOARD: True
    EXPERIMENT_LOG_DIR:
    FLUSH_EVERY_N_MIN: 20
  CHECKPOINT:
    DIR:
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 10
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TRAIN:
      DATA_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 128
      LABEL_TYPE: sample_index    # just an implementation detail. Label isn't used
      TRANSFORMS:
        - name: ImgReplicatePil
          num_times: 2
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
          p: 0.5
        - name: ImgPilColorDistortion
          strength: 1.0
        - name: ImgPilGaussianBlur
          p: 0.5
          radius_min: 0.1
          radius_max: 2.0
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      COLLATE_FUNCTION: moco_collator
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      DROP_LAST: True
  #    TEST:
  #      DATA_SOURCES: [disk_folder]
  #      #      DATA_PATHS: ["<path to test folder>"]
  #      LABEL_SOURCES: [disk_folder]
  #      DATASET_NAMES: [imagenet1k_folder]
  #      BATCHSIZE_PER_REPLICA: 256
  #      TRANSFORMS:
  #        - name: Resize
  #          size: 256
  #        - name: CenterCrop
  #          size: 224
  #        - name: ToTensor
  #        - name: Normalize
  #          mean: [0.485, 0.456, 0.406]
  #          std: [0.229, 0.224, 0.225]
  MODEL:
    TRUNK:
      NAME: vision_transformer
      TRUNK_PARAMS:
        VISION_TRANSFORMERS:
          IMAGE_SIZE: 224
          PATCH_SIZE: 16
          NUM_LAYERS: 12
          NUM_HEADS: 12
          HIDDEN_DIM: 768
          MLP_DIM: 3072
          DROPOUT_RATE: 0
          ATTENTION_DROPOUT_RATE: 0
          CLASSIFIER: token
    HEAD:
      PARAMS: [
      ["mlp", {"dims": [768, 1000]}],
      ]
    AMP_PARAMS:
      USE_AMP: True
      # USE_AMP: True
      AMP_ARGS: {"opt_level": "O1"}
  METERS:
    name: ""
  #    accuracy_list_meter:
  #      num_meters: 1
  #      topk_values: [1, 5]
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 1
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
