# @package _global_
config:
  DATA:
    TRAIN:
      TRANSFORMS:
        - name: Resize
          size: [256, 256]
        - name: CenterCrop
          size: 227
        - name: RandomHorizontalFlip
        - name: ImgPilToRawTensor
        - name: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [1.0, 1.0, 1.0]
    TEST:
        TRANSFORMS:
          - name: Resize
            size: [256, 256]
          - name: CenterCrop
            size: 227
          - name: ImgPilToRawTensor
          - name: Normalize
            mean: [123.675, 116.28, 103.53]
            std: [1.0, 1.0, 1.0]
  MODEL:
    TRUNK:
      NAME: alexnet_bvlc
      LINEAR_FEAT_POOL_OPS: [
          ["AvgPool2d", [[19, 19], 4, 0]],
          ["AvgPool2d", [[12, 12], 3, 0]],
          ["AvgPool2d", [[9, 9], 1, 0]],
          ["AvgPool2d", [[9, 9], 1, 0]],
          ["AvgPool2d", [[8, 8], 1, 0]],
      ]
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 96, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 8142]}],
        ["eval_mlp", {"in_channels": 384, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 384, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 8142]}],
      ]
      BATCHNORM_MOMENTUM: 0.001
