 # @package _global_
 config:
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
          WIDTH_MULTIPLIER: 4
      LINEAR_FEAT_POOL_OPS: [
        ['AdaptiveAvgPool2d', [[6, 6]]],
        ['AdaptiveAvgPool2d', [[3, 3]]],
        ['AdaptiveAvgPool2d', [[2, 2]]],
        ['AdaptiveAvgPool2d', [[1, 2]]],
        ['AdaptiveAvgPool2d', [[1, 1]]]
      ]
    HEAD:
      PARAMS: [
        ['eval_mlp', {'in_channels': 256, 'dims': [9216, 205]}],
        ['eval_mlp', {'in_channels': 1024, 'dims': [9216, 205]}],
        ['eval_mlp', {'in_channels': 2048, 'dims': [8192, 205]}],
        ['eval_mlp', {'in_channels': 4096, 'dims': [8192, 205]}],
        ['eval_mlp', {'in_channels': 8192, 'dims': [8192, 205]}]
      ]
