# @package _global_
config:
  DATA:
    TRAIN:
      DATA_SOURCES: [everstore]
      DATASET_NAMES: [instagram_subset_1M]
      USE_STATEFUL_DISTRIBUTED_SAMPLER: True
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: True
      COPY_DESTINATION_DIR: /tmp/instagram_subset_1M/
      DROP_LAST: True
  MACHINE:
    NUM_DATALOADER_WORKERS: 8
