# @package _global_
config:
  DATA:
    TRAIN:
      DATA_SOURCES: [everstore]
      DATASET_NAMES: [instagram_2billion]
      USE_STATEFUL_DISTRIBUTED_SAMPLER: True
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      DROP_LAST: True
  MACHINE:
    NUM_DATALOADER_WORKERS: 8
