 # @package _global_
 config:
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
          WIDTH_MULTIPLIER: 3
      LINEAR_FEAT_POOL_OPS: [
          ########## res50-w3 #############
          ["AdaptiveAvgPool2d", [7]],
          ["AdaptiveAvgPool2d", [[4, 3]]],
          ["AdaptiveAvgPool2d", [[3, 2]]],
          ["AdaptiveAvgPool2d", [[3, 1]]],
          ["AdaptiveAvgPool2d", [[2, 1]]],
      ]
    HEAD:
      PARAMS: [
        ########## res50-w3 #############
        ["eval_mlp", {"in_channels": 192, "dims": [9408, 205]}],
        ["eval_mlp", {"in_channels": 768, "dims": [9216, 205]}],
        ["eval_mlp", {"in_channels": 1536, "dims": [9216, 205]}],
        ["eval_mlp", {"in_channels": 3072, "dims": [9216, 205]}],
        ["eval_mlp", {"in_channels": 6144, "dims": [12288, 205]}],
      ]
