# @package _global_
config:
  DATA:
    TRAIN:
      BATCHSIZE_PER_REPLICA: 64
  OPTIMIZER:
    param_schedulers:
      lr:
        base_value: 19.2
        name: composite
        schedulers:
          - name: linear
            start_value: 0.6
            end_value: 19.2
          - name: cosine
            start_value: 19.2
            end_value: 0.0000
  DISTRIBUTED:
    NUM_NODES: 32
    NUM_PROC_PER_NODE: 8
