# @package _global_
config:
  VERBOSE: False
  LOG_FREQUENCY: 10
  TEST_ONLY: False
  TEST_MODEL: False
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  MONITOR_PERF_STATS: True
  ROLLING_BTIME_FREQ: 313
  PERF_STAT_FREQUENCY: 10
  #  TEST_EVERY_NUM_EPOCH: 1
  #  TEST_MODEL: True
  TENSORBOARD_SETUP:
    USE_TENSORBOARD: True
    EXPERIMENT_LOG_DIR: "/checkpoint/ito/vision_transformer/simclr/1gpu_test"
    LOG_ACTIVATIONS: False
    FLUSH_EVERY_N_MIN: 20
  CHECKPOINT:
    DIR: "/checkpoint/ito/vision_transformer/simclr/1gpu_test"
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 1
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TRAIN:
      DATA_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 2
      LABEL_TYPE: sample_index    # just an implementation detail. Label isn't used
      TRANSFORMS:
        - name: ImgReplicatePil
          num_times: 2
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
          p: 0.5
        - name: ImgPilColorDistortion
          strength: 1.0
        - name: ImgPilGaussianBlur
          p: 0.5
          radius_min: 0.1
          radius_max: 2.0
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      COLLATE_FUNCTION: simclr_collator
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      DROP_LAST: True
  #    TEST:
  #      DATA_SOURCES: [disk_folder]
  #      #      DATA_PATHS: ["<path to test folder>"]
  #      LABEL_SOURCES: [disk_folder]
  #      DATASET_NAMES: [imagenet1k_folder]
  #      BATCHSIZE_PER_REPLICA: 256
  #      TRANSFORMS:
  #        - name: Resize
  #          size: 256
  #        - name: CenterCrop
  #          size: 224
  #        - name: ToTensor
  #        - name: Normalize
  #          mean: [0.485, 0.456, 0.406]
  #          std: [0.229, 0.224, 0.225]
  MODEL:
    TRUNK:
      NAME: vision_transformer
      TRUNK_PARAMS:
        VISION_TRANSFORMERS:
          name: vit_h_14
          DROPOUT_RATE: 0.1
          ATTENTION_DROPOUT_RATE: 0
          CLASSIFIER: token
    HEAD:
      PARAMS: [
      ["mlp", {"dims": [1280, 5120], "use_relu": True, "use_bn": True,
               "use_bias": False}],
      ["mlp", {"dims": [5120, 5120], "use_relu": True, "use_bn": True, "use_bias": False}],
      ["mlp", {"dims": [5120, 128]}],
      ]
  LOSS:
    name: simclr_info_nce_loss
    simclr_info_nce_loss:
      temperature: 0.1
      buffer_params:
        embedding_dim: 128
  OPTIMIZER:
    name: adamw
    weight_decay: 0.3
    #    momentum: 0.9
    num_epochs: 90
    #    nesterov: True
    #    regularize_bn: False
    #    regularize_bias: True
    param_schedulers:
      lr:
        #        auto_lr_scaling: # learning rate is automatically scaled based on batch size
        #          auto_scale: true
        #          base_value: 0.1
        #          base_lr_batch_size: 256 # learning rate of 0.1 is used for batch size of 256
        name: composite
        schedulers:
          - name: linear
            start_value: 0.0
            end_value: 0.003
          - name: cosine
            start_value: 0.003
            end_value: 0
        interval_scaling: [rescaled, fixed]
        update_interval: step
        lengths: [0.1, 0.9]
  GRAD_CLIP:
    USE_GRAD_CLIP: True
  METERS: null
  #    accuracy_list_meter:
  #      num_meters: 1
  #      topk_values: [1, 5]
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 1 # 1 GPU
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
